services:
  owrx:
    image: 'docker.io/slechev/openwebrxplus-softmbe:latest'
    container_name: owrx-mbe
    restart: unless-stopped
    ports:
      - '8073:8073'
    environment:
      TZ: Europe/Sofia
      OPENWEBRX_ADMIN_USER: myuser
      OPENWEBRX_ADMIN_PASSWORD: password
    devices:
      - /dev/bus/usb:/dev/bus/usb
    # volumes:
    #   - /opt/owrx-docker/etc:/etc/openwebrx
    #   - /opt/owrx-docker/var:/var/lib/openwebrx
    #   - /opt/owrx-docker/plugins:/usr/lib/python3/dist-packages/htdocs/plugins