apiVersion: akri.sh/v0
kind: Configuration
metadata:
  name: {{ .Values.akriConfig.configurationName }}
spec:
  capacity: 1
  discoveryHandler:
    discoveryDetails: |
      groupRecursive: true # Recommended unless using very exact udev rules
      udevRules:
      {{- range .Values.akriConfig.usbDevices }}
      - ATTRS{idVendor}=="{{ .idVendor }}", ATTRS{idProduct}=="{{ .idProduct }}"
      {{- end}}
    name: udev