apiVersion: akri.sh/v0
kind: Configuration
metadata:
  name: akri-sdr
spec:
  capacity: 1
  discoveryHandler:
    discoveryDetails: |
      groupRecursive: true # Recommended unless using very exact udev rules
      udevRules:
      - ATTRS{idVendor}=="0bda", ATTRS{idProduct}=="2838"
    name: udev